import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/context/AuthContext'
import "bootstrap/dist/css/bootstrap.min.css";
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
//import "primereact/resources/themes/lara-light-cyan/theme.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
    
      <body>
        <AuthProvider>
          <PrimeReactProvider>
        {children}
        </PrimeReactProvider>
        </AuthProvider>
        </body>
        
    </html>
   
  )
}
